name: Deploy to Kubernetes

on:
  workflow_call:
    inputs:
      docker-registry:
        type: string
        required: true
      image:
        type: string
        required: true
      build-args:
        type: string
        description: "List of build-time variables"
        required: false
      context:
        type: string
        description: "Build's context is the set of files located in the specified PATH or URL"
        required: false
    secrets:
      docker-username:
        required: true
      docker-password:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ inputs.docker-registry }}/${{ inputs.image }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value={{branch}}-{{sha}}-{{date 'X'}}

      - name: Login to Docker registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.docker-registry }}
          username: ${{ secrets.docker-username }}
          password: ${{ secrets.docker-password }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.context }}
          push: ${{ github.event_name != 'pull_request' }}
          build-args: ${{ inputs.build-args }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ steps.meta.outputs.tags }}
          cache-to: type=inline
